### ISSUE TITLE
 export the total numbe

### ISSUE THREAD

**Issue by AleksKavil** [BlenderBoi/Frame_Ranger#5]
After I use this to load all animations, exporting all animations does not export the total number of keyframes of the animation itself

**Comment by KamilSucharski** [comment]
@AleksKavil Did you solve it? I'm having a similar issue, where the last frame is missing for all animations.

**Comment by BlenderBoi** [comment]
Last Frame is missing? Do you Have any Video are explanation so I can understand the problem better?

**Comment by KamilSucharski** [comment]
I've created a sample .blend file so that you can experience the issue that I have - after baking of the Action1 animation I'm not getting last keyframe in Baked_Action1 animation. I've also included a video showing what I mean by that. Needed to zip it for Github.

Blender version: 3.6.4
Addon version: 3.1.0
[sample.zip](https://github.com/BlenderBoi/Frame_Ranger/files/12906199/sample.zip)

**Comment by BlenderBoi** [comment]
Interesting, Probably a bug somewhere, For now the workaround will be just add one more frame for manual frame range I think

I will try to make a patch next weekend

Can't believe someone actually knows how to use the that Action Baker, I thought no one uses that

**Comment by KamilSucharski** [comment]
For now my workaround is to use the Game Rig Tool, which doesn't have this issue, but baking is much slower there and I prefer the UI of Frame Ranger, so I'm awaiting your fix.

**Comment by BlenderBoi** [comment]
Patched in v3.1.1 for Fixing Action Baker Baking Last Frame

Download Link:
https://github.com/BlenderBoi/Frame_Ranger/releases/tag/v3.1.1
